video-server-domain: "http://tlumn.b0.upaiyun.com/"
sd-video-server-domain: "http://tlumn.b0.upaiyun.com/"
photo-server-domain: "http://tlimage.b0.upaiyun.com/"
photo-exif-domain: "http://imgcdn.tlum.net/"

title: "ZE3kr"
description: "Welcome!"
small-avatarurl: "https://tlimage.b0.upaiyun.com/thrideo/ze3kr_s.jpg"
avatarurl: "https://tlimage.b0.upaiyun.com/thrideo/ze3kr.jpg"
branch: master
itunes: https://itunes.apple.com/podcast/id907999392?at=10lJIS
copyright: CC BY-NC-SA 3.0.
copyright_link: https://creativecommons.org/licenses/by-nc-sa/3.0/

markdown: kramdown
permalink: /:year/:month/:title/

paginate: 15
paginate_path: "page/:num/"

gems:
  - jekyll-redirect-from
  - jekyll-archives

jekyll-archives:
  enabled: 
  - year
  - month
  - categories

  layouts: 
    categories: archive
    month: archive-month
    year: archive-year

  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

keep_files: 
  - CNAME
  - .git